In [1]:
import h5py
import tkinter as tk
from tkinter import filedialog
import numpy as np
import tifffile

root = tk.Tk()
root.withdraw()
gt_file_path = filedialog.askopenfilename()

# gt_file = h5py.File(gt_file_path, 'r+')
# gt_image = np.array(gt_file['project_data'].get('raw_image'))
# gt_label = np.array(gt_file['project_data'].get('label'))

gt_label = tifffile.imread(gt_file_path).astype(np.uint16)


root = tk.Tk()
root.withdraw()
pred_file_path = filedialog.askopenfilename()

# pred_file = h5py.File(pred_file_path, 'r+')
# pred_image = np.array(pred_file['project_data'].get('raw_image'))
# pred_label = np.array(pred_file['project_data'].get('label'))

pred_label = tifffile.imread(pred_file_path).astype(np.unint16)




ValueError: no files found

: 

In [8]:
pred_label[pred_label>2] = 0
np.unique(pred_label)

array([0, 1, 2])

In [9]:
gt_label[gt_label>2] = 0
np.unique(gt_label)

array([0, 1, 2])

In [7]:
SCRIPT_DIR = os.path.dirname(os.path.abspath(__vsc_ipynb_file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))

from processing.processing_functions import *

In [17]:
from monai.metrics import compute_meandice
import torch

dim_order = (0,4,1,2,3)

pred_cat = to_categorical_torch(pred_label, 3)
gt_cat = to_categorical_torch(gt_label,3)

pred_cat = torch.permute(torch.unsqueeze(pred_cat,0),dim_order)
gt_cat = torch.permute(torch.unsqueeze(gt_cat, 0),dim_order)

In [18]:
pred_cat.shape

torch.Size([1, 3, 35, 512, 512])

In [19]:
dice_scores = compute_meandice(pred_cat, gt_cat, include_background=True)

In [22]:
dice_scores

tensor([[0.9980, 0.2619, 0.5840]])

In [23]:
pred_file.close()
gt_file.close()

: 